# Build
dest: _gh_pages


# Site metadata
title: Example Pagination
lead: false
description: Pagination examples for Assemble

# License info
license:
  type: MIT License
  url: ./license/index.html


# URLs
blog: http://assemble.io/blog/
repo: https://github.com/assemble/example-pagination
download:
  source: <%= site.repo %>/archive/master.zip


# SEO/SEM
google:
  analytics: false
  site_id: false


# Comments
disqus:
  shortname: assemble-example-pagination


# Social
social:
  twitter:
    via: jonschlinkert
    username: assemble
  facebook: false
  gplus: false
  hn: false
  google: false


# Sharing
social:
  twitter: false
  facebook: false
  gplus: false
  hn: false
  google: false

